#!/bin/sh

if [[ $# -lt 1 ]]; then
    echo "usage: compile-x86 [-h] FILE"
    echo "error: too few arguments"
    exit 1
elif [[ -z "$1" ]] || [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]; then
    echo "usage: compile-x86 [-h] FILE"
    echo ""
    echo "Compile a Micro Objective-C source file to an ELF x86-32 executable"
    echo ""
    echo "optional arguments:"
    echo "  -h, --help  show this help message and exit"
else
    rm -f /tmp/p.moc /tmp/p.x86 /tmp/p.o "${1%.*}" &&
    ./preprocessor.py "$1" /tmp/p.moc &&
    ./mocc -m x86 /tmp/p.moc &&
    nasm -f elf /tmp/p.x86 &&
    ld -m elf_i386 -o "${1%.*}" /tmp/p.o
fi
