#!/bin/sh

if [[ $# -lt 1 ]]; then
    echo "usage: compile-craps [-h] FILE"
    echo "error: too few arguments"
    exit 1
elif [[ -z "$1" ]] || [[ "$1" = "-h" ]] || [[ "$1" = "--help" ]]; then
    echo "usage: compile-craps [-h] FILE"
    echo ""
    echo "Compile a Micro Objective-C source file to a CRAPS asm file"
    echo ""
    echo "optional arguments:"
    echo "  -h, --help  show this help message and exit"
else
    MOC_DIR=$(dirname "${BASH_SOURCE[0]}")
    rm -f /tmp/p.moc /tmp/p.asm "${1%.*}.asm" &&
    cpp -traditional-cpp -nostdinc -Wall -I. -C -P "$1" /tmp/p.moc &&
    "$MOC_DIR"/mocc -m craps /tmp/p.moc &&
    cp /tmp/p.asm "${1%.*}.asm"
fi
