#!/bin/sh

#--------------------------------------------------------
# root directory
ROOTDIR=`dirname "$0"`
#--------------------------------------------------------
# associated jars
EJAR=eggc-6.0.0.jar
#--------------------------------------------------------
# java, javac, jar
JDIR=/usr/bin

$JDIR/java -ea -classpath "$ROOTDIR:$ROOTDIR/$EJAR" moc.compiler.MOCC $*
